# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &ZG
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ZGMSP

        # ID to load the MSP definition as
        ID: ZGMSP

        MSPDir: crypto-config/peerOrganizations/zg.com/msp
        
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ZGMSP.admin', 'ZGMSP.peer', 'ZGMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ZGMSP.admin', 'ZGMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ZGMSP.admin')"
        
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.zg.com
              Port: 7051