version: '2'

networks: 
  business_blockchain:

services:

  ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-zg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.zg.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c5b7a21e7f1655980285c378b7ad83723dd8e3242163136dfb83db64b6ca25e9_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.zg.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c5b7a21e7f1655980285c378b7ad83723dd8e3242163136dfb83db64b6ca25e9_sk -b admin:adminpw -d'
    volumes:
      - ./channel-artifacts/crypto-config/peerOrganizations/zg.com/ca/:/etc/hyperledger/fabric-ca-server-config
    extra_hosts:
      - "peer0.zg.com:192.168.1.116"
    container_name: ca.zg.com
    networks:
      - business_blockchain