version: '2'

networks:
  business_blockchain:

services:

  ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-datascience
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.datascience.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/fad93d545074a8473265f5a35064e3123c65df598457102d177cd3c2435ce95a_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -c /etc/hyperledger/fabric-ca-server/ca-server-config.yaml --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.datascience.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/fad93d545074a8473265f5a35064e3123c65df598457102d177cd3c2435ce95a_sk -b dsadmin:dsadminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/datascience.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./ca-config/:/etc/hyperledger/fabric-ca-server
    # IP address of all peers of the same organisation
    extra_hosts:
      - "peer0.datascience.com:192.168.1.105"
    container_name: ca.datascience.com
    networks:
      - business_blockchain