# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  business_blockchain:

services:

  cli-datascience:
    container_name: cli-datascience
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli-datascience
      - CORE_PEER_ADDRESS=peer0.datascience.com:7051
      - CORE_PEER_LOCALMSPID=DataScienceMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/datascience.com/peers/peer0.datascience.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/datascience.com/peers/peer0.datascience.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/datascience.com/peers/peer0.datascience.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/datascience.com/users/Admin@datascience.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      # - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    extra_hosts:
      - "nbpOrderer1.nbp.com:192.168.1.105"
      - "nbpOrderer2.nbp.com:192.168.1.105"
      - "nbpOrderer3.nbp.com:192.168.1.105"
      - "nbpOrderer4.nbp.com:192.168.1.105"
      - "nbpOrderer5.nbp.com:192.168.1.105"
      - "peer0.eclinic.com:192.168.1.100"
    networks:
      - business_blockchain
