version: '2'

networks:
  business_blockchain:

services:

  ca:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-eclinic
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.eclinic.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f551124026f22cb25843a4627c27c5f5c36933f70dbe343864aae1257b6ab542_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.eclinic.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f551124026f22cb25843a4627c27c5f5c36933f70dbe343864aae1257b6ab542_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/eclinic.com/ca/:/etc/hyperledger/fabric-ca-server-config
    # IP address of all peers of the same organisation
    extra_hosts:
      - "peer0.eclinic.com:192.168.1.100"
    container_name: ca.eclinic.com
    networks:
      - business_blockchain